spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: false
  flyway:
    locations:
      - classpath:flyway
    table: flyway_history
  mail:
    host: smtp.gmail.com
    port: 587
    username: javamailsender2021@gmail.com
    password: ctkkgoqmnxcjbcxn
    properties.mail.smtp:
      auth: true
      starttls.enable: true

security:
  first_key: 123
  second_key: qwe


scheduled:
  cron: 0 * * * * *
telegram:
  bot:
    name: UserServiceApplicationBot
    token: 1908229986:AAGQ16j5VPbU5nkABtsDAH4ElDK1SlKb4xU
  channelId: -1001522687995
